agent:
  frames_to_update: 2000
  save_dir: "train/treechop/"
  update_quantity: 600
  update_target_net_mod: 10000
  batch_size: 32
  margin: 0.4
  replay_start_size: 20000
  gamma: 0.99
  learning_rate: 0.0001
  n_step: 10

buffer:
  size: 450000
  episodes_to_decay: 50
  min_demo_proportion: 0.

wrappers:
  frame_stack: 4
  frame_skip: 4

model_name: "minerl_dqfd"
tb_dir: "train/tboard/"

pretrain:
  steps: 150000
  min_demo_reward: 60.0

episodes: 200
